### ISSUE TITLE
[Enhancement] Add execution of single tfvars file to rover

### ISSUE THREAD

**Issue by angde1990** [aztfmod/rover#108]
rover will execute all tfvars files in the folder specified by the **var-folder** flag. This is not practical if I want to execute single tfvars file in pipeline for different approval groups. It will be great if there is a **var-file** flag that only execute a single tfvars file.

**Comment by arnaudlh** [comment]
hi @angde1990 have you tried ```-var-file```?

**Comment by angde1990** [comment]
@arnaudlh you are right Arnaud, `-var-file` works fine, closing this issue
