### ISSUE TITLE
Unable to pickup tfvars.json files from -var-folder path.

### ISSUE THREAD

**Issue by suneetnangia** [aztfmod/rover#113]
To be able to transform the parameters dynamically, we use the json version of the files. Currently, rover does not use tfvars.json files present in -var-folder path.
To get around this we use terraform.tfvars.json which gets picked up by Terraform implicitly, we could potentially use -var-file directly in rover cmdline but it's not ideal.

I'll be raising a PR for this change soon.

**Comment by LaurentLesle** [comment]
Closing the issue as merged
