### ISSUE TITLE
Fix developer experience when developing rover using the dev container.

### ISSUE THREAD

**Issue by rguthriemsft** [aztfmod/rover#123]
We found that when you open the rover project in vscode and then launch the dev container, it was overwriting the /tf/rover contents.  This issue is to track fixes to fix developing rover inside the dev container.

Acceptance Criteria:
- [ ] Fix the dev container to support developing rover
- [ ] Document the dev experience for others to decrease effort to quickly get up and developing for rover.
- [ ] Test that PR also works on codespace before submitting PR.

**Comment by LaurentLesle** [comment]
Closing as not more activities on it
