### ISSUE TITLE
URL Dead Link (404) for "Open source landing zones"

### ISSUE THREAD

**Issue by DanGiffen** [aztfmod/rover#18]
https://github.com/aztfmod/rover/blob/landingzones

**Comment by LaurentLesle** [comment]
Hi @DanGiffen where did you find that URL? it should be https://github.com/aztfmod/landingzones

**Comment by LaurentLesle** [comment]
ok found it on the readme. thanks going to fix it. should be https://github.com/aztfmod/landingzones

**Comment by DanGiffen** [comment]
> ok found it on the readme. thanks going to fix it. should be https://github.com/aztfmod/landingzones

Great, thanks @LaurentLesle
