### ISSUE TITLE
Support auto nonlock feature during plan with rover

### ISSUE THREAD

**Issue by seanlok** [aztfmod/rover#201]
Implementing automatically non lock state for tfstate feature with `-lock=false` when the `-a plan`, so that minimal permission to be granted at the containers / blob level to perform a plan.

This should only be in plan action NOT apply.

**Comment by LaurentLesle** [comment]
Thanks for the suggestion. This applies well to the caf_platform_contributors who can work on improving the deployed platform and check their modifications without being able to apply their changes.

caf_platform_contributors has "Storage Blob Data Reader"
