### ISSUE TITLE
Rover login error

### ISSUE THREAD

**Issue by jasonpanggit** [aztfmod/rover#206]
![image](https://user-images.githubusercontent.com/73123860/135791865-8a830c97-4cbf-40a6-82b9-548874f97ef6.png)

Rebuilding the container and images, logout and rebooted Docker Desktop doesn't work. There is no issue on another laptop with the same rover version.

**Comment by jasonpanggit** [comment]
Network related issue

**Comment by jasonpanggit** [comment]
Apparently updating to Docker Desktop v4.01 causes this problem

**Comment by arnaudlh** [comment]
Indeed @jasonpanggit, crossrefing https://github.com/Azure/caf-terraform-landingzones/issues/250
