### ISSUE TITLE
Failed to persist state when internet connectivity lost

### ISSUE THREAD

**Issue by iriahk89** [aztfmod/rover#24]
![image](https://user-images.githubusercontent.com/19380966/80562490-7c744980-8a1a-11ea-8892-fa479fac17f7.png)

getting above error when disconnecting from internet for some time. Its will be better if we able to recover the tfstate file from errored.tfstate. Below is the sample of errored.tfstate created when failing

![image](https://user-images.githubusercontent.com/19380966/80562580-acbbe800-8a1a-11ea-9781-5e136a38aec8.png)

**Comment by arnaudlh** [comment]
Closing as this has been implemented.
