### ISSUE TITLE
Update to Microsoft Graph API Queries

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/rover#245]
When running rover with latest Azure CLI, you get the following messages: 

![image](https://user-images.githubusercontent.com/20535201/158764509-83aed488-d8c8-4fe9-a241-0420a36a66d3.png)

```bash
WARNING: The underlying Active Directory Graph API will be replaced by Microsoft Graph API in a future version of Azure CLI. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration
```
The cause is a set of queries in rover to locate objects, that are relying on Azure AD Graph API queries as such: 
![image](https://user-images.githubusercontent.com/20535201/158764693-0ed63cdb-0a27-4cc5-b43c-197f7095a1de.png)

```bash
az ad signed-in-user show --query userPrincipalName -o tsv
``` 

Purpose of this issue is to track the replacement of all the Azure AD Graph API to Microsoft Graph API if needed.

**Comment by sharmilamusunuru** [comment]
Hi Arnaud,

I have tested this query over azure betaCLI which is compatible with Microsoft Graph API, and below command is working fine. :)

(tutorial-env) C:\Users\smusunuru\Singtel>azcli --version
'azcli' is not recognized as an internal or external command,
operable program or batch file.

(tutorial-env) C:\Users\smusunuru\Singtel>az --version
azure-cli                2.34.1.post20220325082216

core                     2.34.1.post20220325082216
telemetry                1.0.6.post20220325082216

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0

Python location 'C:\Users\smusunuru\Singtel\tutorial-env\Scripts\python.exe'
Extensions directory 'C:\Users\smusunuru\.azure\cliextensions'

Python (Windows) 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

(tutorial-env) C:\Users\smusunuru\Singtel>az ad signed-in-user show --query userPrincipalName -o tsv
The underlying Active Directory Graph API will be replaced by Microsoft Graph API in Azure CLI 2.37.0. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration
smusunuru@microsoft.com
