### ISSUE TITLE
Rover login okay, but failed to run a plan

### ISSUE THREAD

**Issue by jamesyoung007** [aztfmod/rover#258]
Tfstates subscription set to 8bc5e0b8-97de-44b0-a16c-94b619533cf0 (Visual Studio Enterprise Subscription – MPN)

mode                          : 'login'
terraform command output file : ''
terraform plan output file    : ''
directory cache               : '/home/vscode/.terraform.cache'
tf_action                     : ''
command and parameters        : ''

level (current)               : 'level0'
environment                   : 'sandpit'
workspace                     : 'tfstate'
terraform backend type        : 'azurerm'
tfstate                       : ''
tfstate subscription id       : '8bc5e0b8-97de-44b0-a16c-94b619533cf0'
target subscription           : 'Visual Studio Enterprise Subscription – MPN'
CI/CD enabled                 : 'false'
Symphony Yaml file path       : ''
Run all tasks                 : 'true'
TF_IN_AUTOMATION              : 'true'

@calling process_actions

You can deploy a landingzone with the rover by running:
  rover -lz [landingzone_folder_name] -a [plan|apply|destroy|validate|refresh|graph|import|output|taint|untaint|'state list'|'state rm'|'state show']

@calling clean_up_variables
cleanup variables
clean_up backend_files
➜  caf git:(main) ✗ rover -lz lz -a plan                                                                          

  /$$$$$$   /$$$$$$  /$$$$$$$$       /$$$$$$$
 /$$__  $$ /$$__  $$| $$_____/      | $$__  $$
| $$  \__/| $$  \ $$| $$            | $$  \ $$  /$$$$$$  /$$    /$$/$$$$$$   /$$$$$$
| $$      | $$$$$$$$| $$$$$         | $$$$$$$/ /$$__  $$|  $$  /$$/$$__  $$ /$$__  $$
| $$      | $$__  $$| $$__/         | $$__  $$| $$  \ $$ \  $$/$$/ $$$$$$$$| $$  \__/
| $$    $$| $$  | $$| $$            | $$  \ $$| $$  | $$  \  $$$/| $$_____/| $$
|  $$$$$$/| $$  | $$| $$            | $$  | $$|  $$$$$$/   \  $/ |  $$$$$$$| $$
 \______/ |__/  |__/|__/            |__/  |__/ \______/     \_/   \_______/|__/

              version: aztfmod/rover:1.1.7-2203.2311

@calling verify_azure_session
Checking existing Azure session
Error on or near line 273: No parameters have been set in landingzone.; exiting with status 1

**Comment by LaurentLesle** [comment]
Closing as no answer
