### ISSUE TITLE
No Azdo runner agents in Ubuntu 22.04

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/rover#277]
Xrefing: https://github.com/microsoft/azure-pipelines-agent/issues/3834 
Since migrated to Ubuntu 22.04

**Comment by dsfrederic** [comment]
@arnaudlh can you describe this issue a little bt more? 

I'm currently encountering an issue that might be related. #280

**Comment by LaurentLesle** [comment]
Still getting with 2.211.1 the following error:
![image](https://user-images.githubusercontent.com/4702224/198885547-65d3474d-a43a-4b02-b055-0cc452fa02c2.png)

**Comment by sschne** [comment]
Ubuntu 22.04 will be supported from version 3 of Azure pipeline agents, see https://devblogs.microsoft.com/devops/upgrade-of-net-agent-for-azure-pipelines/

**Comment by arnaudlh** [comment]
Closing as resolved!
