### ISSUE TITLE
Add kubelogin to the Docker file 

### ISSUE THREAD

**Issue by nusrath432** [aztfmod/rover#299]
To access Private AKS and missing features from Kubectl can we add https://github.com/Azure/kubelogin, please

PR: https://github.com/aztfmod/rover/pull/305

**Comment by arnaudlh** [comment]
hi @nusrath432, are you able to submit a PR or want me to add to team backlog? :)

**Comment by nusrath432** [comment]
@arnaudlh only if you hiring me full-time ;)

https://github.com/aztfmod/rover/pull/305

**Comment by arnaudlh** [comment]
> @arnaudlh only if you hiring me full-time ;)
> 
> PR: #305

you overestimate my power @nusrath432 ;) but thanks for the PR :)
