### ISSUE TITLE
Update rover components failing due to new golang version formatting. 

### ISSUE THREAD

**Issue by rodmhgl** [aztfmod/rover#337]
It looks like something recently changed with the golang version response resulting in a (partial) timestamp being added to the current parsed output. This issue is causing the [update components pipeline](https://github.com/aztfmod/rover/actions/runs/5848853330) to fail. 

```
# Current method of parsing
~/projects/rover$ version=$(curl -sSL https://golang.org/VERSION?m=text | cut -c 3-)
~/projects/rover$ echo $version 
1.21.0 me 2023-08-04T20:14:06Z
```

```
# Unparsed response
~/projects/rover$ curl -sSL https://golang.org/VERSION?m=text
go1.21.0
time 2023-08-04T20:14:06Z
```

**Comment by arnaudlh** [comment]
closing as PR merged, thanks for your contribution @rodmhgl
