### ISSUE TITLE
[feature] Add rover support for multiple subscriptions

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/rover#37]
In order to support multi subscriptions deployment mode, add rover support for additional fields including:
- Subscription_ID
- Tenant_ID

1. Write the specs to support multiple remote backend - one for the Level 0 TF state and the other one for the deployment (where is the level0 [subscription, storage account...], where is the current state for the deployment)
2. validate the specs - needs at least 2 reviewers
3. implement the code in the rover
4. unit and integration test
5. automation (Azure DevOps and GitHub Actions)

**Comment by Jawz84** [comment]
Me and my colleagues would love to use this functionality. If there is any way in which we could contribute to this, let me know. We would be happy to test-drive early versions for instance. Thanks.
