### ISSUE TITLE
kubernetes-xenial main 404

### ISSUE THREAD

**Issue by sujitks** [aztfmod/rover#374]
We are getting 404 error where it is trying to pull some packages from google.

E: The repository 'https://apt.kubernetes.io kubernetes-xenial Release' no longer has a Release file.

![image](https://github.com/aztfmod/rover/assets/1211513/84092edb-9e10-4b2a-a676-c58d2f4c42f2)

**Comment by arnaudlh** [comment]
should be fixed already @sujitks! please reopen if not!
