### ISSUE TITLE
[feature] Allow launchpad to be pull dynamically from GitHub

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/rover#38]
In current design, for stability reasons, a rover version is tied to a snapshot in time of the level0/launchpad. 

This issue is to change this behaviour and to get code from launchpad repository dynamically.

**Comment by hieumoscow** [comment]
Fix running docker within rover without sudo should also fix this

**Comment by arnaudlh** [comment]
This feature is introduced in rover 2006.xxxx: the launchpad are now included into the landing zones repository. When you clone landing zones, you clone the required launchpad at the same time.
See: https://github.com/Azure/caf-terraform-landingzones and https://github.com/Azure/caf-terraform-landingzones/tree/vnext/landingzones/launchpad
