### ISSUE TITLE
functions.sh,  function plan(),  missing var-file

### ISSUE THREAD

**Issue by MilanNXT** [aztfmod/rover#39]
shell script functions.sh 
function plan()
terraform plan is called without var-file
subsequently incorrect names used during apply

during bootstrap var-file is passed to launchpad.sh
When "deploying from scratch", var-file is not passed to initialize_state function in functions.sh and subsequently to above mentioned plan and apply causing default values being used for names in launchpad_opensource (level0 repo).

**Comment by LaurentLesle** [comment]
@MilanNXT can you share the command you used?
