### ISSUE TITLE
consider specific version of providers instead of latest in docker build

### ISSUE THREAD

**Issue by eissko** [aztfmod/rover#42]
Hello Folks, 

it would be worth to consider explicit tag when cloning azuredevops provider (https://github.com/aztfmod/rover/blob/1e1c15cb3c78c79c83acdb2d7341f6258bad3476/Dockerfile#L59) in docker build. 

the concern I have is the docker image of rover every time it is built even from the same commit it does not need to be idempotent due to "dynamic" clone of the **latest code** from different repository of azuredevops provider instead of cloning specific version.

maybe it is intentional but I don't see benefit. 

I have come into the problem that I have built the rover again today, from the same code base and couldn't pass the bootstrap steps of caf foundation which were working the days before.

after investigation I realized that there is clone from different repo as I described above. 

and what is more. the investigation had been difficult because in container when I attached inside, unfortunately - there is used hard-coded value in the name of azure devops provider - more here issue reported - https://github.com/microsoft/terraform-provider-azuredevops/issues/341

this could be also fix on this codebase -  (https://github.com/aztfmod/rover/blob/1e1c15cb3c78c79c83acdb2d7341f6258bad3476/Dockerfile#L46) when before executing build.sh you overwrite file PROVIDER_VERSION.txt :

```
`# to force the docker cache to invalidate when there is a new version
ADD "https://api.github.com/repos/microsoft/terraform-provider-azuredevops/git/ref/tags/v${versionAzureDevopsTerraform}" version.json

RUN cd /tmp && \
git clone --branch "v${versionAzureDevopsTerraform}" https://github.com/microsoft/terraform-provider-azuredevops.git && \
cd terraform-provider-azuredevops && \
echo ${versionAzureDevopsTerraform} > PROVIDER_VERSION.txt && \
./scripts/build.sh
```

**Comment by arnaudlh** [comment]
hi @eissko, understand the pain point, we'll look to have a short term fix for it, happy to get a PR on it :). Also we are quite looking forward to use registry sourcing for the providers as a longer term solution: https://www.hashicorp.com/blog/adding-provider-source-to-hashicorp-terraform/

**Comment by LaurentLesle** [comment]
@eissko terraform-provider-azuredevops started implementing releases recently so we will transition to their releases soon.
