### ISSUE TITLE
to consider - upload launchpad state even if terraform apply fails

### ISSUE THREAD

**Issue by eissko** [aztfmod/rover#43]
Hello Folks,
bear with me if I am missing some information but when deploying launchpad first time, and it creates X resoruces and if fails on resource X+1 as an example - on error that X+1 resource already exists in azure cloud, then the tf state is not uploaded to the storage and we have to manually go through azure portal and delete all X resource which has been created. and run launchpad again.

would it be possible in this section of code below, in function initialize_state add concept of try and catch? 

even if apply fails, don't exit bash script at all but execute "upload_state" even partial?
https://github.com/aztfmod/rover/blob/1e1c15cb3c78c79c83acdb2d7341f6258bad3476/scripts/functions.sh#L192

I am not geek in bash but that would be quite easy using command1 || command2.

thanks

Peter

**Comment by LaurentLesle** [comment]
Yes you are correct. If the process fails during the state initialization you have to do a manual clean-up of the deployed resources before re-trying to deploy the launchpad.

A more robust approach is required as you highlight. Happy to get some contributions here if it is a show stopper.

**Comment by arnaudlh** [comment]
Hi @eissko this one should be addressed in 2007 rover build release. 
Please provide us feedback if it does not resolve.
