### ISSUE TITLE
limitation of having one launchpad per subscription due to hardcoded tags.workspace=="level0"

### ISSUE THREAD

**Issue by eissko** [aztfmod/rover#44]
Hello Folks,
we wanted to have more launchpads within one subscription as separation between environments (dev,test,...). We fast run into the problem when deloying second launchpad because the pipeline always find existing one because it is done by filter based on resource type = storage account with tags: tfstate=level0 & workspace=level0.

Here is reference to the code:
https://github.com/aztfmod/rover/blob/1e1c15cb3c78c79c83acdb2d7341f6258bad3476/scripts/functions.sh#L197

As easy fix it would be to make the tag "workspace" as parameter instead of expect value "level0" which is hardcoded - that's limitation for 1 launchpad per 1 subscription.

**Comment by LaurentLesle** [comment]
Hi @eissko launchpad is not designed to manage an environment but the remote tfstates. If you need multiple environments you can create multiple workspaces

launchpad workspace create <name of the workspace>

then when you run the rover you can use the -w <name of the workspace> to target your environment.

you have an advanced example here https://github.com/aztfmod/level0/blob/master/.github/workflows/ci-branches.yml

So from now we are going to keep this design of 1 level0/workspace level0 per sub.

**Comment by eissko** [comment]
"to keep this design of 1 level0/workspace level0 per sub" - fair enough. thank you for clarification.
