### ISSUE TITLE
Rover Launchpad Error

### ISSUE THREAD

**Issue by fireblade95402** [aztfmod/rover#6]
Hi

Yesterday it seemed to be working ok. Today when I create the launchpad "./rover.sh" it runs through and then has the following error: 

`Error: Error reading queue properties for AzureRM Storage Account "tfstatelvz8kdrtv33ip0flk": queues.Client#GetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "\ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:2d7d39f0-b003-0073-55cc-a6737f000000\nTime:2019-11-29T15:48:02.5881860Z</Message><AuthenticationErrorDetail>Request date header too old: 'Fri, 29 Nov 2019 13:04:34 GMT'</AuthenticationErrorDetail></Error>" error: invalid character 'ï' looking for beginning of value

  on storage.tf line 24, in resource "azurerm_storage_account" "stg":
  24: resource "azurerm_storage_account" "stg" {
`

Help on this would be great.

Cheers,

Mark

**Comment by LaurentLesle** [comment]
Thanks @fireblade95402  for reporting the error. This is currently an error we have seen on Windows 10 with newer docker desktop build 2.1+. When a vscode remote container running on your local windows 10 and your computer is going to sleep mode, you end-up after few cycle sleep / resume to have the clock of the container that is not updated. This drift cause the error "Request date header too old".

Try to quit Docker desktop and restart as a workaround and re-open your local dev container.

You can check the drift by running the command in your container
```
date
```

and on you local windows 10 powershell
```
$(Get-Date).ToUniversalTime()
```
A significant difference would confirm the time drift.

There is open issue on the docker desktop for windows https://github.com/docker/for-win/issues/4526

I will keep that issue opened until the docker desktop issue is sorted out.

**Comment by Masahigo** [comment]
> Thanks @fireblade95402 for reporting the error. This is currently an error we have seen on Windows 10 with newer docker desktop build 2.1+. When a vscode remote container running on your local windows 10 and your computer is going to sleep mode, you end-up after few cycle sleep / resume to have the clock of the container that is not updated. This drift cause the error "Request date header too old".
> 
> Try to quit Docker desktop and restart as a workaround and re-open your local dev container.
> 
> You can check the drift by running the command in your container
> 
> ```
> date
> ```
> 
> and on you local windows 10 powershell
> 
> ```
> $(Get-Date).ToUniversalTime()
> ```
> 
> A significant difference would confirm the time drift.
> 
> There is open issue on the docker desktop for windows [docker/for-win#4526](https://github.com/docker/for-win/issues/4526)
> 
> I will keep that issue opened until the docker desktop issue is sorted out.

I can confirm this issue is still valid.

**Comment by LaurentLesle** [comment]
@fireblade95402 @Masahigo running the following command fixes the time drift when returning from sleep mode

`sudo hwclock -s` from wsl2 when resuming from sleep mode resynch the clock in the dev containers. At least I don't have to reboot Windows 10.

**Comment by arnaudlh** [comment]
Closing as it works fine on every OS now :)
