### ISSUE TITLE
Add support for standard container environments

### ISSUE THREAD

**Issue by zolty** [aztfmod/rover#63]
Centos7 really isn't a popular container choice. Please port this to Debian and Alpine.

**Comment by sandeeplamb** [comment]
Also, I want to point out towards the Dockerfile.
Is there some specific reason, we are Installing git from source code?
yum can do same magic. configure takes time to create full image.

**Comment by LaurentLesle** [comment]
the ubuntu base image is very small 47MB. The size is coming from the tooling required to deploy various scenarios (az cli, kubectl, terraform, docker cli, ansible, python3..) to name few of the toolbox in the rover.
