### ISSUE TITLE
Cannot deploy launchpad-100 if not the owner of subscription

### ISSUE THREAD

**Issue by singh-rahul** [aztfmod/rover#66]
I was classic service administrator, but not owner of subscription. Was getting permission error on tfstate storage account, which was fixed by adding roles as owner in subscription.  A validation script to develop for validating all the prerequisites in subscription before creating the launchpad.

**Comment by xpillons** [comment]
@singh-rahul Even being an owner I'm getting an error too. Any idea how to solve this ?

Error: Error checking for existence of existing Container "tfstate" (Account "boqsstlevel0yodgp" / Resource Group "boqs-rg-launchpad-tfstates-yodgp"): containers.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationPermissionMismatch" Message="This request is not authorized to perform this operation using this permission.\nRequestId:93b64880-301e-0042-5bf2-8c24b6000000\nTime:2020-09-17T12:58:24.3992341Z"

**Comment by singh-rahul** [comment]
@xpillons The other reason could be datetime synchronization in Docker desktop on Windows machine. Try synchronizing the time in WSL with this command -  "sudo hwclock -s"

**Comment by xpillons** [comment]
I was not in the ower role group while being an owner of the sub. I added myself the owner role and I can deploy now.
