### ISSUE TITLE
Install Packer binaries in the Rover container

### ISSUE THREAD

**Issue by benhurjoel** [aztfmod/rover#76]
Requesting to add the Packer binaries in the Rover container as there are requirements to create Custom Images. 

Instructions to be included :
-------------------------------
sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
sudo yum -y install packer-${versionPacker}
cd /usr/bin
sudo mv packer packer.io   #CentOS has an existing package by the same name; so Packer has to be renamed.

ref : https://learn.hashicorp.com/tutorials/packer/getting-started-install?in=packer/getting-started

Thank you.

**Comment by benhurjoel** [comment]
@LaurentLesle The Packer version to be specified is 1.6.4 (packer-1.6.4)

**Comment by Justin-DynamicD** [comment]
I think its just as safe to just drop an alias in the .bashrc as thats specific to the user space wheras "the other packer" is used by the system.

At any rate, I noticed this as well and ultimately just made a custom container for the company that adds the missing pieces .  The entire dockerfile could look like this:

```
ARG versionRover

FROM ${versionRover} as base

# note these MUST be unique from existing ENV in base
# or they will be ignored
ARG versionPacker

###
# Install Packer
###
RUN echo "Installing packer ${versionPacker}..." && \
    sudo curl -sSL -o ./packer.zip https://releases.hashicorp.com/packer/${versionPacker}/packer_${versionPacker}_linux_amd64.zip && \
    sudo unzip -d /usr/bin ./packer.zip && \
    sudo chmod +x /usr/bin/packer && \
    sudo rm ./packer.zip && \
    echo "alias packer=/usr/bin/packer" >> /home/${USERNAME}/.bashrc

[...]
```

Add to it with nomad or other tools you want included, and just call the rover version you want with the leading arg.

**Comment by LaurentLesle** [comment]
Thanks Justin. I have created an alpha version of the rover aztfmod/roveralpha:2010.140651
I put packer in the /usr/local/bin so it is picked-up without having to specify the alias in the .bashrc
We should have a vnext later this week

**Comment by benhurjoel** [comment]
Thank you @LaurentLesle . It's working.
