### ISSUE TITLE
QUESTION: what is the purpose to mounting a shared volume?

### ISSUE THREAD

**Issue by Justin-DynamicD** [aztfmod/rover#77]
So in each example of the rover I see, there is mounting of `volume-caf-vscode` over the vscode home directory.

What gets stored there?  Is it simply so that container upgrades dont force you to re-init?  Does the rover actually store/expect values in that location? Are there any negative reprocussions to leaving it out?

Logic: I have multiple clients and if they use the default devcontainer settings its basicaly possible to cross contaminate as each of thier repos would attempt to mount the same shared volume on my workstation.  Id rather void this by editing out the shared volume mount if possible, but dont want ot break anythign permanent.

**Comment by LaurentLesle** [comment]
Hi Justin. We map a local docker volume to store your local cache for az session, bash history, ssh keys, caching terraform plugins. We found this improve the developer experience. This is something docker recommend also when you need to write data to get good speed as opposed to writing in the container directly. When your laptop resume from sleep and you return to the vscode remote container you can recall previous commands and also benefit from the cache. To avoid cross-contamination you need to store the configuration from different client in different directories and vscode will create a specific volume based on the concatenation of the folder and the volume-caf-vscode.

**Comment by Justin-DynamicD** [comment]
Thank you for the clarification!
