### ISSUE TITLE
Ansible inaccessible from vscode user

### ISSUE THREAD

**Issue by Justin-DynamicD** [aztfmod/rover#80]
The Dockerfile currently installs ansible 2.10 using pip3, but it does so while logged in as root.  This results in the ansible binary being located at `/root/.local/bin/ansible` which is inaccesable from the default vscode user.

Aside from that, Ansible documentation still says that 2.9 should continue to be used on RHEL distros at this time, so I'm not 100% certain this installation would even be reliable:
[Link](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-rhel-centos-or-fedora)

>Since Ansible 2.10 for RHEL is not available at this time, continue to use Ansible 2.9.

Suggestion: please fall back on the standard yum/2.9 installation that can then be accessible from the default vscode user.

**Comment by arnaudlh** [comment]
hi @Justin-DynamicD we have issued an new version of rover that should resolve that, you can use: ```aztfmod/roverdev:2010.141511```. Please let us know if it resolves the issue.

**Comment by Justin-DynamicD** [comment]
Confirmed: as vscode I can load 2.9.13:

```
[vscode@74a922efb9ed rover]$ ansible --version
ansible 2.9.13
  config file = None
  configured module search path = ['/home/vscode/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
