### ISSUE TITLE
landingzone list produces ForbiddenError

### ISSUE THREAD

**Issue by jleonelion** [aztfmod/rover#93]
I was receiving the below error when running: ' rover landingzone list' with container version aztfmod/rover:2010.2808 
```
ForbiddenError: 
Authentication failure. This may be caused by either invalid account key, connection string or sas token value provided for your storage account.
```
I dug through shell scripts to narrow down the cause.  It looks like the SAS token used to list contents of storage account is surrounded by double quotes, and then surrounded by single quotes when later passed to `az storage blob list`

Please assign to me and I can submit PR with the fix.

**Comment by arnaudlh** [comment]
hi @jleonelion working in my environment - are you running on WSL2? did you check the timesync between your host and container - this sometimes happen due to clock skew...

**Comment by LaurentLesle** [comment]
I have tried with the latest rover version. working as well

![image](https://user-images.githubusercontent.com/4702224/100974184-d1f77280-3576-11eb-9752-61d55fcdff39.png)

**Comment by jleonelion** [comment]
I've updated the version of rover to 2011.3012 and the problem is gone.  It looks like the shell scripts within rover container have been changed quite a bit so I'm closing out this issue.

I'll open a separate issue in the caf-terraform-landingzones-starter project to update .devcontainer/docker-compose.yml so the new version of rover is used.

**Comment by arnaudlh** [comment]
thanks for the feedback @jleonelion
